### ISSUE TITLE
同样的部署方式，存在一些情况部分数据拿不到

### ISSUE THREAD

**Issue by froglian** [sunny0826/cms-grafana-builder#21]
![image](https://user-images.githubusercontent.com/16535660/120667874-7de72f80-c4c0-11eb-9f3b-2fea986f23cf.png)
如图所示，发现有时候部分数据拿不到。

部署方式确定可以，而且其他AK是可以的，只有部分AK不行。另外因为有一些数据可以拿到，不是权限的问题。这个有遇到过不？问题可能是什么呢？

**Comment by sunny0826** [comment]
方便看一下日志吗？

**Comment by sunny0826** [comment]
目前看来 AK/AS 就没有问题的，应该是这个 top10 接口的问题

**Comment by froglian** [comment]
status:500
statusText:"Internal Server Error"
data:Object
error:"Internal Server Error"
response:" <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html> <head> <title>Error: 500 Internal Server Error</title> <style type="text/css"> html {background-color: #eee; font-family: sans;} body {background-color: #fff; border: 1px solid #ddd; padding: 15px; margin: 15px;} pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;} </style> </head> <body> <h1>Error: 500 Internal Server Error</h1> <p>Sorry, the requested URL <tt>&#039;http://howard-content-tokyo-cms-variable/query&#039;</tt> caused an error:</p> <pre>Internal Server Error</pre> </body> </html> "
message:"Internal Server Error"
message:"Internal Server Error"
--

日志是500
我找阿里云的同学帮忙搜了一下ak的请求，发现网关上没有失败日志，疑似请求并未到阿里云

**Comment by froglian** [comment]
我看variable的pod没啥问题，有点奇怪，我理解这个variable的服务是部署在本地。但是我多次重新部署这个服务，好像也没有效果。

**Comment by sunny0826** [comment]
这个 top 10 是通过 variable 调用阿里云 OpenAPI 的接口，能看到 variable 的日志吗？

**Comment by froglian** [comment]
10.70.221.177 - - [04/Jun/2021 06:35:30] "POST /query HTTP/1.1" 200 72
10.70.221.177 - - [04/Jun/2021 06:35:30] "POST /query HTTP/1.1" 200 72
10.70.221.177 - - [04/Jun/2021 06:35:30] "POST /search HTTP/1.1" 200 77
10.70.221.177 - - [04/Jun/2021 06:35:31] "POST /search HTTP/1.1" 200 77
10.70.221.177 - - [04/Jun/2021 06:35:32] "POST /search HTTP/1.1" 200 77
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 108, in query
    datapoints = [[cpu_list[i]['Average'], cpu_list[i]['timestamp']]]
IndexError: list index out of range
10.70.221.177 - - [04/Jun/2021 06:35:32] "POST /query HTTP/1.1" 500 755
--

额，刚复现了一下，variable是有错误，但是看不到阿里云的返回码。从阿里云网关上看，好像没有收到请求，是不是没发出来?

**Comment by froglian** [comment]
日志是在GMT+0时区拿的

**Comment by sunny0826** [comment]
请求应该是收到了，是 cpu top10 内有其他的内容 `list index out of range` 了，你的云监控有接非阿里云的机器吗？

**Comment by froglian** [comment]
我是这么部署的
我有一个容器集群，也是在阿里云上。然后会创建多个namespace，不同的namespace下会部署不同AKSK/region helm chart。
不同ns下部署方式除了aksk不同其他都一样，但是有的就可以有的就不行。不过不同AKSK代表不同账号嘛，这个账号下的云监控具体怎么用的我暂时还不能查看。

你是说这个AK下的云监控有接入非阿里云的机器，所以导致通过cms拿数据的时候有问题？

**Comment by sunny0826** [comment]
之前有遇到过这种情况，不过你的这个可能是权限问题

**Comment by froglian** [comment]
我有查过。。权限应该没问题。我特意看了一下，有两个账号的RAM是一样的权限策略，然后一个没问题，一个会报这个internal error..

list index out of range  麻烦简单介绍下呗，这个top10这里原理大概是咋做的，我按这个逻辑分析下，是不是账号哪里配置或者有特殊情况

**Comment by sunny0826** [comment]
这里 top10 就是调了阿里云 OpenAPI 的接口，然后根据 grafana 的要求格式化了一下，这里这个问题是格式化时候的问题

**Comment by froglian** [comment]
所以其实是拿到数据了，但是这个数据有点问题不符合之前定义的格式。那这个还真是有点麻烦。

**Comment by sunny0826** [comment]
对，一般情况我可以自己 debug，但是你这个情况我没法帮忙
