### ISSUE TITLE
面板显示没有数据，但是弹性公网IP的有数据过来

### ISSUE THREAD

**Issue by vuzemin** [sunny0826/cms-grafana-builder#9]
sunny，您好！
![image](https://user-images.githubusercontent.com/49711566/80557315-17fcbe80-8a09-11ea-959d-a110fe79dc71.png)
![image](https://user-images.githubusercontent.com/49711566/80557357-3662ba00-8a09-11ea-9a60-4f24a14c8e61.png)
面板显示没有数据，但是弹性公网IP的有数据过来。不知道哪些地方需要修改

**Comment by sunny0826** [comment]
ECS页面请选择实例名称，不用管IP，IP只是做展示使用

**Comment by vuzemin** [comment]
就是没有读取到实例ID
![image](https://user-images.githubusercontent.com/49711566/80561710-e3dcca00-8a17-11ea-93e1-14f48e1195b5.png)
但是在单个插件面板下能看到实例ID，但是变量没获取到值
![image](https://user-images.githubusercontent.com/49711566/80561746-07077980-8a18-11ea-9372-e26f14d13ada.png)

**Comment by sunny0826** [comment]
你的机器有实例描述吗？

**Comment by vuzemin** [comment]
有的

**Comment by sunny0826** [comment]
这是一个bug，我修复一下

**Comment by sunny0826** [comment]
bug 已经修复了，见：https://github.com/sunny0826/cms-grafana-builder/releases/tag/v0.3.1

**Comment by vuzemin** [comment]
好的。辛苦了，我重新安装试下

**Comment by vuzemin** [comment]
sunny,您好，这个计划任务主要是用来干嘛的有？ 
cronjob.batch/my-release-cms-cronjob   30 2 * * *

**Comment by sunny0826** [comment]
定时刷新资源的，之前的版本是实时调用阿里云OpenAPI获取资源信息，但是访问的量太大熔断了，所以现在使用的是本地sqlite存储，定时刷新资源

**Comment by vuzemin** [comment]
哦，还是接收不到实例信息
![image](https://user-images.githubusercontent.com/49711566/80576183-527d5000-8a37-11ea-95bf-43137536cb1f.png)
另外nodeport我是修改了sevice.yaml文件的spec，这样是否有问题？ 
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 32767
      protocol: TCP
      name: http

**Comment by sunny0826** [comment]
装的事`0.3.1`吗？

**Comment by vuzemin** [comment]
是这个版本。
![image](https://user-images.githubusercontent.com/49711566/80577877-329b5b80-8a3a-11ea-8639-7318ecbe4643.png)

**Comment by sunny0826** [comment]
我这边试了好几次，好像没法复现

**Comment by vuzemin** [comment]
不知道是不是阿里云帐号ID权限的问题，需要授权哪些权限：云监控只读和ECS只读够了吗？

**Comment by sunny0826** [comment]
还包括了RDS、OSS、redis、VPC等资源的读取

**Comment by scottyungit** [comment]
> sunny，您好！
> ![image](https://user-images.githubusercontent.com/49711566/80557315-17fcbe80-8a09-11ea-959d-a110fe79dc71.png)
> ![image](https://user-images.githubusercontent.com/49711566/80557357-3662ba00-8a09-11ea-9a60-4f24a14c8e61.png)
> 面板显示没有数据，但是弹性公网IP的有数据过来。不知道哪些地方需要修改

请问你这个问题解决了吗？

**Comment by sunny0826** [comment]
可以到后端服务`xxx-cms-variable`里面看一下日志，是否有报错

**Comment by vuzemin** [comment]
![image](https://user-images.githubusercontent.com/49711566/82533706-661f6080-9b76-11ea-9df5-87cff7949ff8.png)

**Comment by vuzemin** [comment]
10.244.1.30 - - [21/May/2020 07:25:43] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:25:44] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:25:49] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:25:54] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:26:04] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:26:14] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:26:24] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:26:34] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:26:34] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:26:37] "POST /search HTTP/1.1" 200 47
10.244.1.30 - - [21/May/2020 07:26:42] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:26:44] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:26:45] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:26:54] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:26:54] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:27:04] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:27:14] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:27:20] "POST /search HTTP/1.1" 200 89
10.244.1.30 - - [21/May/2020 07:27:20] "POST /search HTTP/1.1" 200 47
10.244.1.30 - - [21/May/2020 07:27:24] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:27:24] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:27:28] "POST /search HTTP/1.1" 200 47
10.244.1.30 - - [21/May/2020 07:27:33] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:27:34] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:27:44] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:27:54] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:04] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:14] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:24] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:34] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:44] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:28:54] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:29:04] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:29:14] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:29:24] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:29:25] "POST /search HTTP/1.1" 200 47
10.244.1.30 - - [21/May/2020 07:29:28] "POST /search HTTP/1.1" 200 47
10.244.3.1 - - [21/May/2020 07:29:34] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:29:44] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:29:54] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:29:59] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:29:59] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:30:04] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:30:06] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:30:06] "POST /search HTTP/1.1" 500 756
10.244.1.30 - - [21/May/2020 07:30:11] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:30:11] "POST /search HTTP/1.1" 500 756
10.244.1.30 - - [21/May/2020 07:30:14] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:30:14] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:30:14] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:30:24] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:30:34] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:30:44] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:30:54] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:31:02] "POST /search HTTP/1.1" 200 77
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:31:02] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:31:04] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:31:05] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:31:05] "POST /search HTTP/1.1" 500 756
10.244.1.30 - - [21/May/2020 07:31:10] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:31:10] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:31:14] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:31:23] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:31:23] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:31:24] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [21/May/2020 07:31:34] "GET / HTTP/1.1" 200 2
10.244.1.30 - - [21/May/2020 07:31:35] "POST /search HTTP/1.1" 200 77
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.1.30 - - [21/May/2020 07:31:40] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [21/May/2020 07:31:44] "GET / HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range

**Comment by sunny0826** [comment]
这个日志是没有数据，应该是没有ECS的权限

**Comment by vuzemin** [comment]
![image](https://user-images.githubusercontent.com/49711566/82543876-ce763e00-9b86-11ea-9e44-7e83d45b04a2.png)
![image](https://user-images.githubusercontent.com/49711566/82543910-dcc45a00-9b86-11ea-8d3b-2c4b99517426.png)
![image](https://user-images.githubusercontent.com/49711566/82543987-fb2a5580-9b86-11ea-8bdd-6587a36b91fd.png)

ECS授权了，但是这里还是显示None

**Comment by vuzemin** [comment]
![image](https://user-images.githubusercontent.com/49711566/82544289-7ee44200-9b87-11ea-840c-575e0036554e.png)

**Comment by sunny0826** [comment]
重新部署一下吧，应该是数据没有同步到sqlite中，ECS的表是空的

**Comment by vuzemin** [comment]
重新部署了。

**Comment by vuzemin** [comment]
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080
E0522 11:07:08.870242    8992 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod 562feb8959e99dbe5ca01aabf2e859a27b9124b0d4cb141b1fd6f6be141d1e5f, uid : exit status 1: 2020/05/22 11:07:08 socat[19779] E connect(9, AF=2 127.0.0.1:80, 16): Connection refused

**Comment by vuzemin** [comment]
![image](https://user-images.githubusercontent.com/49711566/82629163-76404a00-9c21-11ea-8a33-cd67d231dfaa.png)

**Comment by vuzemin** [comment]
10.244.3.50 - - [22/May/2020 03:42:52] "POST /search HTTP/1.1" 500 756
10.244.3.1 - - [22/May/2020 03:42:55] "GET / HTTP/1.1" 200 2
10.244.3.50 - - [22/May/2020 03:42:56] "POST /search HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 66, in search
    body = values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:42:56] "POST /search HTTP/1.1" 500 756
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 83, in search
    body = [str({"instanceId": values[0][0]})]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:42:56] "POST /search HTTP/1.1" 500 756
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:43:04] "POST /search HTTP/1.1" 200 238
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 131, in query
    name = get_instance_name(mem_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:05] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 126, in query
    name = get_instance_name(cpu_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:05] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 115, in query
    name = get_instance_name(mem_list[i]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:05] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 136, in query
    name = get_instance_name(disk_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:05] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 109, in query
    name = get_instance_name(cpu_list[i]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:05] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 121, in query
    name = get_instance_name(disk_list[i]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:43:06] "POST /query HTTP/1.1" 500 755
10.244.3.1 - - [22/May/2020 03:43:06] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:43:15] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:43:25] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:43:35] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:43:45] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:43:55] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:44:05] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:44:15] "GET / HTTP/1.1" 200 2
10.244.3.1 - - [22/May/2020 03:44:25] "GET / HTTP/1.1" 200 2
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 3
10.244.3.50 - - [22/May/2020 03:44:30] "POST /search HTTP/1.1" 200 238
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 131, in query
    name = get_instance_name(mem_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:44:32] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 126, in query
    name = get_instance_name(cpu_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:44:32] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 115, in query
    name = get_instance_name(mem_list[i]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:44:33] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 121, in query
    name = get_instance_name(disk_list[i]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range
10.244.3.50 - - [22/May/2020 03:44:33] "POST /query HTTP/1.1" 500 755
Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python3.7/site-packages/cli/runner.py", line 136, in query
    name = get_instance_name(disk_list[0]['instanceId'])
  File "/usr/local/lib/python3.7/site-packages/cli/db.py", line 66, in get_instance_name
    return values[0]
IndexError: list index out of range

**Comment by vuzemin** [comment]
重新部署了，授权了

**Comment by vuzemin** [comment]
![image](https://user-images.githubusercontent.com/49711566/82629374-1d24e600-9c22-11ea-9c76-149137e13ae7.png)

**Comment by sunny0826** [comment]
有初始化的日志吗？类似这样
refresh all
init DB
refresh info of rds
rowcount = 32
refresh info of slb
rowcount = 34
refresh info of eip
rowcount = 114
refresh info of redis
rowcount = 9
refresh info of mongodb

**Comment by sunny0826** [comment]
也可以进入容器，执行`cms refresh`命令
